[versions]
# Plugin
android-gradle-plugin 		= "8.2.1"
kotlin 						= "1.9.22"
ktlint 						= "12.0.3"

# Libraries
## Implementation
core-ktx 					= "1.12.0"
appcompat 					= "1.6.1"
material 					= "1.11.0"
constraintlayout 			= "2.1.4"
navigation-fragment-ktx 	= "2.7.6"
navigation-ui-ktx 			= "2.7.6"

## Test Implementation
junit 						= "4.13.2"

## Android Test Implementation
androidx-test-ext-junit 	= "1.1.5"
espresso-core 				= "3.5.1"


[libraries]

[plugins]
