debugBuild:
  stage: debug
  script:
    - ./gradlew assembleDebug
  rules:
    # Commit to main / develop branch
    - if: $CI_COMMIT_BRANCH == "main" ||
          $CI_COMMIT_BRANCH == "develop"
      when: always
      allow_failure: false
    # Commit to feature branch
    - if: '$CI_COMMIT_BRANCH =~ /^feature/'
      when: always
      allow_failure: true
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: always
      allow_failure: false
    # When the MR source is a feature branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature"
      when: manual
      allow_failure: true

releaseBuild:
  stage: release
  script:
    - echo $KEYSTORE_FILE_BASE64 | base64 -d > release.keystore.jks
    - ./gradlew  assembleRelease
  artifacts:
    name: app-release-$CI_COMMIT_SHA
    paths:
      - ./app/build/outputs/apk/release/*.apk
  rules:
    # Commit to main branch
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
      allow_failure: false
    # Commit to feature branch
    - if: '$CI_COMMIT_BRANCH =~ /^feature/'
      when: manual
      allow_failure: true
