debugBuild:
  stage: debug
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - ./gradlew --gradle-user-home ./.gradleHome assembleDebug
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - ./.gradle
      - ./gradle
      - ./.gradleHome
  rules:
    # Commit to main / develop branch
    - if: $CI_COMMIT_BRANCH == "main" ||
          $CI_COMMIT_BRANCH == "develop"
      when: always
      allow_failure: false
    # Commit to feature / fix branch
    - if: $CI_COMMIT_BRANCH =~ "/^feature/" ||
          $CI_COMMIT_BRANCH =~ "/^fix/"     ||
          $CI_COMMIT_BRANCH =~ "/^hotfix/"
      when: always
      allow_failure: true
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: always
      allow_failure: false
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
      when: manual
      allow_failure: true
  interruptible: true

releaseBuild:
  stage: release
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - echo $KEYSTORE_FILE_BASE64 | base64 -d > release.keystore.jks
    - ./gradlew --gradle-user-home ./.gradleHome assembleRelease
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - ./.gradle
      - ./gradle
      - ./.gradleHome
  artifacts:
    name: app-release-$CI_COMMIT_SHA
    paths:
      - ./app/build/outputs/apk/release/*.apk
  rules:
    # Commit to main branch
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
      allow_failure: false
    # Commit to feature / fix branch
    - if: $CI_COMMIT_BRANCH =~ "develop"    ||
          $CI_COMMIT_BRANCH =~ "/^feature/" ||
          $CI_COMMIT_BRANCH =~ "/^fix/"     ||
          $CI_COMMIT_BRANCH =~ "/^hotfix/"
      when: manual
      allow_failure: true
  interruptible: true
