ktlint:
  stage: lint
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - ./gradlew --gradle-user-home ./.gradleHome ktlintCheck
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - ./.gradleHome
  artifacts:
    paths:
      - ./**/build/reports/ktlint/
    expire_in: 1 day
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
  interruptible: true

androidLint:
  stage: lint
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - ./gradlew --gradle-user-home ./.gradleHome lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - ./.gradleHome
  artifacts:
    paths:
      - ./**/build/reports/lint-report.xml
    expire_in: 1 day
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
  interruptible: true

danger:
  stage: lint
  image: ruby:3.2.2-slim-bullseye
  needs: ["ktlint", "androidLint"]
  before_script:
    # Disable global before script
    []
  script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --no-install-recommends --yes git build-essential
    - bundle install
    - bundle exec danger
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
  interruptible: true
