ktlint:
  stage: lint
  script:
    - ./gradlew ktlintCheck
  artifacts:
    paths:
      - app/build/reports/ktlint/
    expire_in: 1 day
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature"

androidLint:
  stage: lint
  script:
    - ./gradlew lint
  artifacts:
    paths:
      - app/build/reports/lint-report.xml
    expire_in: 1 day
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature"

danger:
  stage: lint
  image: ruby:3.2.2-slim-bullseye
  needs: ["ktlint", "androidLint"]
  before_script:
    # Disable global before script
    []
  script:
    - apt-get --quiet update --yes
    - apt-get --quiet install --no-install-recommends --yes git build-essential
    - bundle install
    - bundle exec danger
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature"
