ktlint:
  stage: lint
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - ./gradlew ktlintCheck
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  artifacts:
    paths:
      - ./**/build/reports/ktlint/
    expire_in: 1 day
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
  interruptible: true

androidLint:
  stage: lint
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - ./gradlew lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  artifacts:
    paths:
      - ./**/build/reports/lint-report.xml
    expire_in: 1 day
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
  interruptible: true

danger:
  stage: lint
  image: $CI_REGISTRY_IMAGE/danger:latest
  needs: ["ktlint", "androidLint"]
  script:
    - bundle exec danger
  rules:
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
  interruptible: true
