unitTest:
  stage: test
  tags:
    - saas-macos-medium-m1
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - ./gradlew --gradle-user-home ./.gradleHome testDebugUnitTest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - ./.gradle
      - ./gradle
      - ./.gradleHome
  artifacts:
    name: unit-test-$CI_COMMIT_SHA
    paths:
      - ./**/build/reports/tests/testDebugUnitTest/
    reports:
      junit: ./**/build/test-results/**/TEST-*.xml
  rules:
    # Commit to main / develop branch
    - if: $CI_COMMIT_BRANCH == "main" ||
          $CI_COMMIT_BRANCH == "develop"
    # Commit to feature / fix / hotfix / renovate branch
    - if: $CI_COMMIT_BRANCH =~ "/^feature/" ||
          $CI_COMMIT_BRANCH =~ "/^fix/"     ||
          $CI_COMMIT_BRANCH =~ "/^hotfix/"  ||
          $CI_COMMIT_BRANCH =~ "/^renovate/"
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix / hotfix / renovate branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature/"  ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix/"      ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix/"   ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^renovate/"
  interruptible: true
