unitTest:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    name: unit-test-$CI_COMMIT_SHA
    paths:
      - app/build/reports/tests/testDebugUnitTest/
    reports:
      junit: app/build/test-results/**/TEST-*.xml
  rules:
    # Commit to main / develop branch
    - if: $CI_COMMIT_BRANCH == "main" ||
          $CI_COMMIT_BRANCH == "develop"
    # Commit to feature / fix branch
    - if: $CI_COMMIT_BRANCH =~ "/^feature/" ||
          $CI_COMMIT_BRANCH =~ "/^fix/"     ||
          $CI_COMMIT_BRANCH =~ "/^hotfix/"
    # When the MR target is the main / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ||
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    # When the MR source is a feature / fix branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature" ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^fix"     ||
          $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^hotfix"
