unitTest:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    name: unit-test-$CI_COMMIT_SHA
    paths:
      - app/build/reports/tests/testDebugUnitTest/
  rules:
    # Commit to main / develop branch
    - if: $CI_COMMIT_BRANCH == "main" ||
          $CI_COMMIT_BRANCH == "develop"
